name: "Automated License Compliance Checker"
description: "Scans projects for license compliance using Scancode Toolkit."

author: "Soheil Borhani <soheil.borhani@gmail.com>"
branding:
  color: "blue"
  icon: "shield"

inputs:
  allowed_licenses:
    description: "Comma-separated list of allowed licenses (e.g., MIT, Apache-2.0, BSD-3-Clause)."
    required: false
    default: "MIT, Apache-2.0, BSD-3-Clause"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.allowed_licenses }}

permissions:
  contents: read  # Read access to repo contents

license: "MIT"