name: License Compliance Check

on: [push, pull_request]


jobs:
  license-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Scancode Docker image
      run: docker build -t scancode-image .

    - name: Run Scancode
      run: |
        docker run --rm -v ${{ github.workspace }}:/app/data scancode-image \
        scancode --license --json-pp /app/data/scan_results.json /app/data

    - name: Upload Scan Results
      uses: actions/upload-artifact@v3
      with:
        name: scan_results.json
        path: scan_results.json