name: License Compliance Check

on: [push, pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml pip-licenses

    - name: Run license checker
      run: python license_checker.py ${{ inputs.allowed_licenses }}
      env:
        ALLOWED_LICENSES: ${{ inputs.allowed_licenses }}

description: "Scans Python projects for license compliance, including dependencies from requirements files and Poetry."
